### ISSUE TITLE
详情pageControl的当前颜色在哪里设置

### ISSUE THREAD

**Issue by ichenwanbing** [was0107/MDetailFramework#6]
详情pageControl的当前颜色在哪里设置，谢谢。

**Comment by cynthiaPu** [comment]
你好，我的轮播图显示不出来，UIScrollPageControlViewDelegate代理设置了，但不执行，是什么问题？

**Comment by was0107** [comment]
@ichenwanbing 

在reloadData之后，pageControl的创建是延迟创建；
[self.detailView reloadData];
_detailView.imageScrollView.pageControl.pageIndicatorTintColor = [UIColor yellowColor];
_detailView.imageScrollView.pageControl.currentPageIndicatorTintColor = [UIColor blueColor];

**Comment by was0107** [comment]
@cynthiaPu 
照demo进行编写

**Comment by ichenwanbing** [comment]
👍 谢谢




发自网易邮箱大师
在2017年03月29日 17:03，Allen 写道：

Closed #6.
